config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about' => 'home#about'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
    resources :discussions, only: [:create, :destroy, :index, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  patch "/projects/:project_id/mark_done/:id" => "tasks#mark_done", as: :mark_done_task

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new, :edit, :update, :show]
  get "/password" => "users#edit_password", as: :edit_password
  patch "/password" => "users#update_password", as: :update_password


  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: [:index]
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {maximum: 255}, uniqueness: {scope: :project_id}
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :find_project, only: [:create, :destroy, :index, :edit, :update]
  before_action :find_discussion, only: [:edit, :update, :destroy]
  before_action :new_comment, only: [:edit, :index]

  def create
    @discussion = Discussion.new discussion_params
    @discussion.project = @project

    if @discussion.save
      redirect_to project_discussions_path(@project), notice: "Discussion Created"
    else
      render :index
    end

  end

  def index
    @discussion = Discussion.new
  end

  def edit
    render :index
  end

  def update
    if @discussion.update discussion_params
      redirect_to project_discussions_path(@project), notice: "Disucssion updated"
    else
      flash[:alert] = "Discussion not updated"
      render :index
    end
  end


  def destroy
    @discussion.destroy
    redirect_to project_discussions_path(@project), notice: "Discussion Deleted"
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :description)
  end

  def find_project
    @project = Project.find params[:project_id]
  end

  def find_discussion
    @discussion = Discussion.find params[:id]
  end

  def new_comment
    @comment = Comment.new
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_comment_form.html.erb
<div>
  <% if discuss == @comment.discussion %>
    <% @comment.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>
</div>

<%= form_for [discuss, @comment], remote: true do |f| %>
  <%= f.text_area :body, placeholder: "Enter your comment..." %>
  <%= f.submit %>
<% end %>

app/views/discussions/_discuss_comment.html.erb
<%# DELETE THIS ???? %>
<br>
<div>

  <%= render "discussions/comment_form", discuss: discuss %>

  <% if discuss.comments.any? %>
    <ul id="comment-list">
      <% discuss.comments.order("created_at DESC").each do |comment| %>
        <%= render 'comments/comment', {discuss: discuss, comment: comment} %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/discussions/_form.html.erb
<% if @discussion.errors.any? %>
<ul>
  <% @discussion.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>


<%= form_for [@project, @discussion] do |f|%>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div>
  <%= f.submit %>
  
  <!-- HOW TO IMPLEMENT??? -->
  <%# "Cancel" if current_page? url_for(edit_project_discussion_path(@projct, @discussion) ) %>
  <%# "Cancel" if current_page?( controller: 'discussion', action: 'edit', project_id: @project.id, id: @discussion.id  ) %>
</div>
<% end %>

app/views/discussions/index.html.erb
<h1><%= @project.title %></h1>

<%= link_to "Back", project_path(@project) %>

<h2>Discussion</h2>

<%= render "discussions/form" %>

<% if @project.discussions.any? %>
  <ul class="discussion-list">

    <% @project.discussions.each do |discuss| %>
    <li>
      <h4 class="title"><%= discuss.title %></h4>
      <p><%= discuss.description %></p>
      <div class="action">
        <%= link_to "Edit", edit_project_discussion_path(@project, discuss) %>

        <%= button_to "Delete", project_discussion_path(@project, discuss),
              method: :delete,
              data: {confirm: "Are you sure?"} %>
      </div>


      <%# render "discussions/discuss_comment", discuss: discuss %>
      <br>
      <div>
        <div id="comment-form">
          <%= render "discussions/comment_form", discuss: discuss %>
        </div>

        <% if discuss.comments.any? %>
          <ul id="comment-list">
            <% discuss.comments.order("created_at DESC").each do |comment| %>
              <%= render 'comments/comment', {discuss: discuss, comment: comment} %>
            <% end %>
          </ul>
        <% end %>
      </div>

    </li>
    <% end %>
  </ul>

<% end %>