config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about' => 'home#about'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
    resources :discussions, only: [:create, :destroy, :index, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  patch "/projects/:project_id/mark_done/:id" => "tasks#mark_done", as: :mark_done_task

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new, :edit, :update, :show]
  get "/password" => "users#edit_password", as: :edit_password
  patch "/password" => "users#update_password", as: :update_password


  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: [:index]
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  after_initialize :set_defaults

  validates :title, presence: true, uniqueness: { scope: :project_id}
  validates :due_date, date: { after: Proc.new { Time.now } }
  validates :body, presence: true
  validates :status, numericality: {only_integer: true}

  # scope :done, -> {where(done: true)}
  # scope :undone, -> {where(done: false)}

  scope :done, -> (done) { where(done: done )  }


  private

  def set_defaults
    self.done ||= false
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def create
    @project = Project.find params[:project_id]
    @task = Task.new task_params
    @task.project = @project

    respond_to do |format|
      if @task.save
        format.html{redirect_to project_path(@project), notice: "Task Created"}
        format.js { render :create_success }
      else
        format.html{render "/projects/show"}
        format.js { render :create_failure }
      end
    end
  end

  def destroy
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
    @task.destroy

    respond_to do |format|
      format.html{redirect_to project_path(@project), notice: "Task Deleted"}
      format.js { render } #this renders /views/tasks/destroy.js.erb
    end
  end

  def mark_done
      @project = params[:project_id]
      @task = Task.find params[:id]
      @task.done = !@task.done
      @task.save
      redirect_to project_path(@project)
  end

  private

  def task_params
    task_params = params.require(:task).permit(:body, :title, :due_date)
  end


end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_done_button(project, task)
    text = task.done? ? "Undone" : "Done"
    button_to text, mark_done_task_path(project, task), method: :patch
  end


end

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
<ul>
  <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [@project, @task], remote: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<tr id="<%= dom_id(task) %>">
  <td><%= task.title %></td>
  <td><%= task.body %></td>
  <td><%= task.due_date.strftime("%B %d, %Y") %></td>
  <td>
    <%= task_done_button(project, task) %>

    <%= button_to "Delete", project_task_path(project, task),
    method: :delete,
    remote: true,
    data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/tasks/create_failure.js.erb
$('#task-form').html("<%= j render 'form' %>")

app/views/tasks/create_success.js.erb
$('#task-list').find('tbody').prepend("<%= j render 'task', {project: @project, task: @task } %>")

<% @task = Task.new %>
$('#task-form').html("<%= j render 'form' %>")

app/views/tasks/destroy.js.erb
$("#<%= dom_id(@task) %>").fadeOut(1000, function() {
  $(this).remove();
});

app/views/tasks/edit.html.erb
<h1>Edit Tasks</h1>

<%= render "form" %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= link_to "Create task", new_task_path %>

<ul>
  <% @task.each do |task|%>
  <li>
    <%= link_to task.title, task_path(task) %>
    <%= task.due_date.strftime("due on %B %d, %Y") %>
  </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<h1>Show Task</h1>

<h2><%= @task.title %></h2>
<p><%= @task.due_date.strftime("due on %B %d, %Y") %></p>

<p><%= link_to "Edit Task", edit_task_path(@task) %></p>

<p><%= link_to "Show all tasks", tasks_path %></p>

<hr>

<p><%= link_to "Delete Task", task_path(@task),
                              method: :delete,
                              date: { confirm: "Are you sure?" } %></p>