config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about' => 'home#about'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
    resources :discussions, only: [:create, :destroy, :index, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  patch "/projects/:project_id/mark_done/:id" => "tasks#mark_done", as: :mark_done_task

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new, :edit, :update, :show]
  get "/password" => "users#edit_password", as: :edit_password
  patch "/password" => "users#update_password", as: :update_password


  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: [:index]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :projects, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_projects, through: :favorites, source: :project

  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :edit_password, :update_password]
  before_action :restrict_signup, only: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Thanks for signing up. Welcome to PMTools!"
    else
      flash[:alert] = "Signup was unsuccessful, please try again"
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update user_params
      redirect_to user_path(@user), notice: "Account updated"
    else
      render :edit
    end
  end

  def edit_password

  end

  def update_password
    if (
        @user.authenticate(params[:user][:current_password]) &&
        check_password?(params[:user][:password], params[:user][:password_confirmation]) &&
        @user.update(user_params)
      )
      redirect_to edit_password_path, notice: "Password updated"
    else
      flash[:alert] = "Wrong Credentials"
      render "users/edit_password"
    end
  end

  private

  def find_user
    # @user ||= User.find params[:id]
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
                            :first_name,
                            :last_name,
                            :email,
                            :password,
                            :password_confirmation)
  end

  def restrict_signup
    redirect_to root_path if user_signed_in?
  end

  def check_password?(password, confirm_password)
    false if password.empty?
    false if confirm_password.empty?
    password == confirm_password ? true : false

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <%= f.submit %>
<% end %>

<hr>

<%= link_to "Change Password", edit_password_path %>

app/views/users/edit_password.html.erb
<h1>Edit Password</h1>

<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, url: update_password_path, method: :patch do |f| %>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Reset Password" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2>Welcome <%= current_user.first_name %></h2>

<%= link_to "Edit Account", edit_user_path(current_user) %>