config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about' => 'home#about'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
    resources :discussions, only: [:create, :destroy, :index, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  patch "/projects/:project_id/mark_done/:id" => "tasks#mark_done", as: :mark_done_task

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new, :edit, :update, :show]
  get "/password" => "users#edit_password", as: :edit_password
  patch "/password" => "users#update_password", as: :update_password


  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: [:index]
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :nullify
  has_many :discussions, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title, presence: true, uniqueness: true
  validates :due_date, date:{ after: Proc.new { Time.now } }

  paginates_per 5

  def favorite_for(user)
    favorites.find_by_user_id user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :destroy, :update]
  # authorize_resource
  # skip_authorize_resource only: [:index, :show]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user,only: [:edit, :update, :destroy]

  # CREATE

  def new
    @project = Project.new
  end

  def create
    # project_params = params.require(:project).permit(:name, :description, :due_date)
    @project = Project.new project_params
    @project.user = current_user

    if @project.save
      redirect_to project_path(@project), notice: "Project created successfully"
    else
      flash[:alert] = "Project wasn't created"
      render :new
    end
  end

  # READ
  def index
    @projects = Project.order("id DESC").page params[:page]
  end

  def show
    # @project = Project.find params[:id]
    @task = Task.new
    @discussion = Discussion.new
  end

  # Update
  def edit
    # @project = Project.find params[:id]
  end

  def update
    # @project = Project.find params[:id]
    if @project.update project_params
      redirect_to project_path(@project), notice: "Project updated successfully"
    else
      flash[:alert] = "Project not updated successfully"
      render :edit
    end
  end

  # Destroy
  def destroy
    # @project = Project.find params[:id]
    @project.destroy

    redirect_to projects_path, notice: "Project Destroyed"
  end

  private

  def project_params
    params.require(:project).permit(:title,:description,:due_date)
  end

  def find_project
    @project = Project.find params[:id]
  end

  def authorize_user
    unless can? :manage, @project
      redirect_to root_path, alert: "Access Denied"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<ul>
  <% @project.errors.full_messages.each do |project| %>
    <li><%= project %></li>
  <% end %>
</ul>

<%= form_for @project do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>

  <%= f.submit %>
<% end %>

app/views/projects/_task_list.html.erb
<table id="task-list">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Due Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% tasks.each do |task| %>
      <%= render "tasks/task", {project: @project, task: task} %>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<p>
  <%= link_to "Back", project_path(@project) %>
</p>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<p><%= link_to "Create Project", new_project_path %></p>

<ul>
  <% @projects.each do |project| %>
  <li>
    <h2><%= link_to project.title, project_path(project) %></h2>
    <p><%= project.description %></p>
    <% if project.due_date.is_a? Time %>
    <%= project.due_date.strftime("due on %B %d, %Y")  %>
    <!-- project.due_date.try(:strftime,"due on %B %d, %Y") -->
    <% else %>
    <%= project.due_date %>
    <% end %>

  </li>
  <% end %>
</ul>

<%= paginate @projects %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= @project.description %></p>

<strong>(<%= @project.favorites.count %> Favorites)</strong>

<% favorite = @project.favorite_for current_user %>

<% if favorite%>
  <%= link_to "Un-Like", project_favorite_path(@project, favorite), method: :delete %>
<% else %>
  <%= link_to "Like", project_favorites_path(@project), method: :post %>
<% end %>

<p>
  <% if can? :manage, @project %>
    <%= link_to "Edit", edit_project_path(@project) %>

    <%= link_to "Delete",
                    project_path(@project),
                    method: :delete,
                    date: { confirm: "Are you sure?" } %>

  <% end %>
</p>

<p>
  <h4><%= link_to "Discussions", project_discussions_path(@project) %></h4>
</p>

<!-- Tasks -->
<hr>
<h2>Tasks</h2>
<div id="task-form">
  <%= render "tasks/form" %>
</div>

<% if @project.tasks.any? %>

  <% if @project.tasks.done(true).any? %>
  <h2>Done Tasks</h2>
    <%= render "projects/task_list", tasks: @project.tasks.done(true), project: @project %>
  <% end %>

  <h2>Undone Tasks</h2>
    <%= render "projects/task_list", tasks: @project.tasks.done(false), project: @project %>
<% end %>


<hr>
<p><%= link_to "Back to Projects", projects_path %></p>